eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8100
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8762/authen/user/info
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: false
ping-server:
  ribbon:
    listOfServers: localhost:8100,localhost:8101
    ServerListRefreshInterval: 15000
