eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8200
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: false
management:
  endpoint:
    health:
      show-details: always

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8762/authen/user/info
