eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 10000
server:
  port: 8762
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 30000
  ignored-services: '*'
routes:
  gallery-service:
    path: /gallery/**
    service-id: gallery-service
  semaphore:
    max-semaphores: 10000
management:
  endpoint:
    health:
      show-details: always
